export const productList = [
  {
    img: "images/moisturizing-mousse.png",
    category: "для нормальной кожи",
    name: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    compoundItems: ["активные натуральные комплексы", "витамины С, А, РР, В И Е", "солнцезащитные компоненты"],
    priceValue: 2750,
    priceDisplay: "2 750",
  },
  {
    img: "images/moisturizing-mask.png",
    category: "для нормальной кожи",
    name: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    compoundItems: ["воски", "минералы", "масла"],
    priceValue: 3500,
    priceDisplay: "3 500",
  },
  {
    img: "images/gel-for-face-washing.png",
    category: "для нормальной кожи",
    name: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    compoundItems: ["минералы", "витамины С, А, РР, В И Е", "солнцезащитные компоненты"],
    priceValue: 1650,
    priceDisplay: "1 650",
  },
  {
    img: "images/gift-set-1.png",
    category: "для нормальной кожи",
    name: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    compoundItems: ["воски", "минералы", "масла"],
    priceValue: 4750,
    priceDisplay: "4 750",
  },
  {
    img: "images/gift-set-5.png",
    category: "для нормальной кожи",
    name: "Подарочный набор №5",
    description: "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    compoundItems: ["воски", "минералы", "масла"],
    priceValue: 7520,
    priceDisplay: "7 520",
  },
];